### ISSUE TITLE
Synthesising Litmus test

### ISSUE THREAD

**Issue by hnemati** [ctrippel/checkmate#1]
Dear Checkmate developers,
Thanks for making the source code publicly available. I am trying to understand how checkmate outputs some litmus test, but I cannot find any tool/command for this. Using Alloy I can generate a model  for specific class of attacks in uarches directory, however I do not know how to generate a litmus test from it. Could you please let me know how I should use checkmate to get litmus test?

Thanks,
-- Hamed

**Comment by ctrippel** [comment]
Hi Hamed,

Thank you for your interest in CheckMate! The litmus tests are listed from left to right at the tops of each of the auto-generated graphs (follow the instructions for generating pngs on the GitHub page). The are essentially the column labels in the synthesized uhb graphs.

Hope this helps!

All the best,

Caroline

On May 17, 2019, at 10:10 AM, hnemati <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Checkmate developers,
Thanks for making the source code publicly available. I am trying to understand how checkmate outputs some litmus test, but I cannot find any tool/command for this. Using Allo I can generate a model for specific class of attacks in uarches directory, however I do not know how to generate a litmus test from it. Could you please let me know how I should use checkmate to get litmus test?

Thanks,
-- Hamed

**Comment by hnemati** [comment]
Hi Caroline,
Thanks for replying! I also managed to get some results using the other tool, litmustestgen, published on your git repo . Does this tool outputs the same result?

Regards,
-- Hamed
