### ISSUE TITLE
hardware details

### ISSUE THREAD

**Issue by cicirori** [ctrippel/checkmate#2]
Hi,
I'm trying to run checkmate on my machine. But it always throw exception: "java.lang.OutOfMemoryError: Java heap space" when using bigger inputs than FiveStage.als. This happened on both my 8G ram win and 16G ram mac. I want to know details about the hardware you used for checkmate. Thank you!

**Comment by ctrippel** [comment]
The lscpu, cpuinfo, and meminfo information for the machine on which I ran my experiments can be found below.

****@****:[~]: lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
Stepping:              2
CPU MHz:               3400.000
CPU max MHz:           3600.0000
CPU min MHz:           1200.0000
BogoMIPS:              6384.83
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-7,16-23
NUMA node1 CPU(s):     8-15,24-31

****@****:[~]: cat /proc/cpuinfo
processor : 0
vendor_id : GenuineIntel
cpu family : 6
model : 63
model name : Intel(R) Xeon(R) CPU E5-2667 v3 @ 3.20GHz
stepping : 2
microcode : 0x3d
cpu MHz : 3400.000
cache size : 20480 KB
physical id : 0
siblings : 16
core id : 0
cpu cores : 8
apicid : 0
initial apicid : 0
fpu : yes
fpu_exception : yes
cpuid level : 15
wp : yes
flags : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc
bogomips : 6384.83
clflush size : 64
cache_alignment : 64
address sizes : 46 bits physical, 48 bits virtual
power management:

****@****:[~]: cat /proc/meminfo
MemTotal:       131563888 kB
MemFree:        97025424 kB
MemAvailable:   117175168 kB
Buffers:               0 kB
Cached:         18584440 kB
SwapCached:       306160 kB
Active:         12748108 kB
Inactive:       14976304 kB
Active(anon):    4929532 kB
Inactive(anon):  5344760 kB
Active(file):    7818576 kB
Inactive(file):  9631544 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       4194300 kB
SwapFree:              0 kB
Dirty:                 8 kB
Writeback:             0 kB
AnonPages:       8833988 kB
Mapped:            39032 kB
Shmem:           1134320 kB
Slab:            3766236 kB
SReclaimable:    3037496 kB
SUnreclaim:       728740 kB
KernelStack:       12992 kB
PageTables:       112716 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    69976244 kB
Committed_AS:   20806160 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      523040 kB
VmallocChunk:   34291052484 kB
HardwareCorrupted:     0 kB
AnonHugePages:   2007040 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      638520 kB
DirectMap2M:    91334656 kB
DirectMap1G:    44040192 kB

On May 27, 2019, at 8:02 AM, cicirori <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I'm trying to run checkmate on my machine. But it always throw exception: "java.lang.OutOfMemoryError: Java heap space" when using bigger inputs than FiveStage.als. This happened on both my 8G ram win and 16G ram mac. I want to know details about the hardware you used for checkmate. Thank you!
